@startuml system_design
top to bottom direction

frame "domain" {
    !include domain.puml
}

frame "data transfer object" {
    class CarParkAvailability
    class NearestCarParkResponse
}

frame "system interaction" {
    class CarParkController {
        + List<NearestCarParkResponse> findNearestCarParks(Coordinate coordinate, Pageable  pageable)
    }

    interface CarParkService {
        + List<CarPark> findNearestCarParks(Coordinate coordinate, Pageable pageable)
        + List<CarPark> saveCarParks(CarPark carParks)
    }

    class DefaultCarParkService {
        + List<CarPark> findNearestCarParks(Coordinate coordinate, Pageable pageable)
        + List<CarPark> saveCarParks(CarPark carParks)
    }

    interface CarParkRepository {
        + List<CarPark> findByIds(List<String> ids)
        + List<CarPark> saveAll(List<CarPark> carParks)
    }

    class SpringJpaCarParkRepository {
        + List<CarPark> findByIds(List<String> ids)
        + List<CarPark> saveAll(List<CarPark> carParks)
    }

    interface DistanceComputer {
        + double computeInMeter(Coordinate from, Coordinate to)
    }

    class LiquibaseCarParkMigrator {
        + void execute()
    }

    class LatLonCoordinateConvert {
        + LatLonCoordinate computeSVY21(SVY21Coordinate svy21)
    }

    interface CarParkAvailabilityClient {
        + CarParkAvailability fetchAvailabilityCarPark();
    }

    class SingaporeCarParkAvailabilityClient  {
        + CarParkAvailability fetchAvailabilityCarPark();
    }

    class EquirectangularDistanceComputer {
        + double computeInMeter(Coordinate from, Coordinate to)
    }
}


CarParkController --* CarParkService
CarParkService <|-- DefaultCarParkService
LiquibaseCarParkMigrator --* CarParkService
DefaultCarParkService --* CarParkRepository
DefaultCarParkService --* CarParkAvailabilityClient
DefaultCarParkService --* DistanceComputer
DistanceComputer <|-- EquirectangularDistanceComputer
CarParkRepository <|-- SpringJpaCarParkRepository
CarParkAvailabilityClient <|-- SingaporeCarParkAvailabilityClient
LiquibaseCarParkMigrator --* LatLonCoordinateConvert
@enduml