spring.application.name: carpark-app

server:
  port: 8080

logging:
  level:
    root: INFO
    com.wego: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  cloud:
    openfeign:
      client:
        config:
          carpark:
            url: "https://api.data.gov.sg/v1"

  datasource:
    url: jdbc:postgresql://localhost:5432/carpark
    username: carpark
    password: carpark@


  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
    open-in-view: false

  liquibase:
    change-log: database/project_model.xml
    parameters:
      csvFilePath: classpath:/HDBCarparkInformation.csv

  cache:
    type: hazelcast

  hazelcast:
    config: classpath:hazelcast.xml
---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres:5432/carpark

logging:
  level:
    root: WARN
    com.wego: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

server:
  port: 80
