spring.application.name: carpark-app

logging:
  level:
    root: INFO
    com.wego: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  cloud:
    openfeign:
      client:
        config:
          carpark:
            url: "https://api.data.gov.sg/v1"

  datasource:
    url: jdbc:postgresql://localhost:5432/carpark
    username: carpark
    password: carpark@
  jpa:
    properties:
      hibernate:
        open-in-view: false
        hbm2ddl:
          auto: validate

  liquibase:
    change-log: database/project_model.xml
    parameters:
      csvFilePath: classpath:/HDBCarparkInformation.csv

spring.datasource.hikari.initializationFailTimeout: 60000